### ISSUE TITLE
Hovering over lines clears highighted terms

### ISSUE THREAD

**Issue by alanhamlett** [sourcegraph/issues#146]
- **Sourcegraph version:** 2.11.0
- **Platform:** Chrome OS X

#### Steps to reproduce:

1. Search a file for a term using browser's built-in page search.
2. Move mouse over a line with a highlighted term, notice the yellow highlight is lost.

#### Expected: 
Terms should stay highlighted.

#### Actual:
Terms incorrectly have yellow background reset on hover.

#### Screenshot:
![sg-bug-search-highlight-persistence](https://user-images.githubusercontent.com/522344/45645334-eb36a600-ba74-11e8-81f1-f4143b2e2535.gif)

**Comment by felixfbecker** [comment]
This is actually somewhat of a Chrome bug - another symptom of this is that in Chrome, if you search for something, then the DOM changes (e.g. on Facebook with load-on-scrolling) and new matches appear, they don't get highlighted until you modify your query to retrigger a search. Since we need to modify the DOM, the highlights get lost (and we have no way to even know they were there). However, we have some plans to not depend on DOM manipulation anymore for certain things which would solve this particular issue. The problem may still appear in different contexts though in Chrome. Firefox does not have this problem.

**Comment by alanhamlett** [comment]
Ok, I'll close this to not clutter up your tracker.
