### ISSUE TITLE
Chrome extension breaks GitHub search style

### ISSUE THREAD

**Issue by beyang** [sourcegraph/issues#21]
https://twitter.com/ahmetb/status/891090924557787137

**Comment by KattMingMing** [comment]
This is due to him having another extension installed that also leverages the GitHub search bar. I'll install that extension and make sure they don't conflict anymore. This only affects users that have https://chrome.google.com/webstore/detail/awesome-autocomplete-for/djkfdjpoelphhdclfjhnffmnlnoknfnd

**Comment by KattMingMing** [comment]
Resolved to make Sourcegraph and Algolia search for GitHub work nicely together
