### ISSUE TITLE
Browser extension fails to offer more actions in Firefox

### ISSUE THREAD

**Issue by beyang** [sourcegraph/issues#37]
This came from a user who emailed support:

- Issue type: bug report
- Sourcegraph version: browser extension (Firefox), Sourcegraph.com
- OS Version: unknown

I cannot click "Click for additional actions...", because the space between the method and the popup is too large: The popup just disappears. No idea for a good solution though...

![image](https://user-images.githubusercontent.com/1646931/35574502-d25e21f8-058e-11e8-92d9-298be36f335e.png)

Example repo: https://github.com/SQiShER/java-object-diff/blob/master/src/main/java/de/danielbechler/diff/comparison/ComparisonConfigurer.java#L44:24

HT @koppor

**Comment by beyang** [comment]
@KattMingMing @ijsnow Thoughts on what could be going on here?

**Comment by koppor** [comment]
Here a short demo video:

![issue37](https://user-images.githubusercontent.com/1366654/35575140-f18c05ac-05db-11e8-9c57-87eff5e7b693.gif)

**Comment by KattMingMing** [comment]
@koppor - When hovering over a token if you click the token it will anchor the popup and reveal the action items. It looks like this may have been a bit confusing due to the text saying "Click for more actions" - Check out the video below demonstrating the implemented behavior.

![browser-actions](https://user-images.githubusercontent.com/4897310/35575666-dc10989a-0591-11e8-8eef-fa0ca45384c8.gif)

We would love it if you test this out and provide additional feedback so we can improve your experience with the browser extension! Thanks for reporting!

**Comment by koppor** [comment]
Thanx! OK, maybe the text "Click for more actions..." should be changed to "Just click there for more actions..." or "Just click for more actions..."

Maybe also the color of the text should change from blue. Typically, hyperlinks are rendered in blue color and one might think that the "Click for more actions..." is a hyperlink.
