### ISSUE TITLE
Go references for RequestType in gousb did not load

### ISSUE THREAD

**Issue by sqs** [sourcegraph/issues#59]
User stapelberg reported that Go references did not load at https://github.com/google/gousb/pull/34#issuecomment-378836342. (Let's avoid at-mentioning the usernamename until it's fixed to avoid wasting their time.)

**Comment by beyang** [comment]
Woah, stapelberg uses Sourcegraph? I use his window manager :)

**Comment by slimsag** [comment]
Because this file is a CGO wrapper to libusb, we do not support code intelligence in it generally (no hover or j2d works), so it is not surprising that references also do not work.

So I believe the real two issues here are:

- [ ] Clicking on a symbol in the sidebar will open the `References` pane even though code intelligence may not be supported in that file -- in which case `References` is surely going to fail. cc @felixfbecker how should we handle this? (should symbols check prior to opening, or should references check itself?)
- [ ] The Go langserver returns `Invalid location` for hovers in CGO files instead of something like `CGO Not supported` or something more clear. Not sure why this is, but I can imagine it is due to some underlying technical complexity with our CGO interaction). Fixing the first issue would be enough to mitigate this.

**Comment by felixfbecker** [comment]
>  Clicking on a symbol in the sidebar will open the References pane even though code intelligence may not be supported in that file -- in which case References is surely going to fail. cc @felixfbecker how should we handle this? (should symbols check prior to opening, or should references check itself?)

Imo the current behaviour is the best, showing an error message why the references cannot be loaded (giving the language server the chance to explain why).
But the error message returned by the go langserver is really bad. Surely it could do better than just saying "Invalid location", I don't even know whether this refers to the line/column or the file. Event "Invalid file" would already be better, but ideally it would say something very clear like "This file is not supported because it has a build tag".

**Comment by slimsag** [comment]
Error message was actually fixed four days ago by @chrismwendt but just wasn't deployed yet :) https://github.com/sourcegraph/go-langserver/commit/4b83e88ae771b0e72b33ae9ecc9c79cd7589fdf8#diff-983a5fb908af9585e71b3179a0dc8596

I've deployed, and you can see the more legible error message here: https://sourcegraph.com/github.com/google/gousb@5115a55a0324bb8a46152070979ec80aa07632a9~1/-/blob/constants.go#L205:6-205:17$references

Once https://github.com/sourcegraph/deploy-sourcegraph/pull/22 is merged this will also be available for our Data Center users.

**Comment by slimsag** [comment]
This was fixed and released for all users.
