### ISSUE TITLE
How to configure the update interval for Git repos?

### ISSUE THREAD

**Issue by ruhullahshah** [sourcegraph/issues#83]
- **Issue type:** Question
- **Sourcegraph version:** 2.7.6
- **Platform:** Docker

By default, Sourcegraph sends an enormous amount of connection requests to our enterprise GitLab server. Currently we control it by setting `disableAutoGitUpdates` to `true` and increasing the duration of `repoListUpdateInterval`.

1) How do I perform a manual update after setting `disableAutoGitUpdates`?

2) How can I tell Sourcegraph to poll a single/(a configurable group) of repository/ies for updates from GitLab periodically after a time interval `(T mins/secs/hours)`?

For more clarity. let us say I have 3 repos and need 
```
 Time     |            Event
    0             Server started
    T               Poll repo 1
   2T               Poll repo 2
   3T               Poll repo 3
   4T               Poll repo 1
```

**Comment by nicksnyder** [comment]
> By default, Sourcegraph sends an enormous amount of connection requests to our enterprise GitLab server

Sorry about that! This is an issue that will be fixed in 2.8 that will be released next week.

For more info read:
- https://github.com/sourcegraph/issues/issues/70#issuecomment-386646196
- https://github.com/sourcegraph/issues/issues/53#issuecomment-389346455

> How do I perform a manual update after setting disableAutoGitUpdates?

1. Go to https://sourcegraph.example.com/YOURCODEHOST/YOURORG/YOURREPO/-/settings/mirror
2. Click "Refresh now"

![screen shot 2018-05-18 at 10 34 21 am](https://user-images.githubusercontent.com/754768/40249216-2608de5e-5a87-11e8-80db-a75ca011f230.png)

> How can I tell Sourcegraph to poll a single/(a configurable group) of repository/ies for updates from GitLab periodically after a time interval (T mins/secs/hours)?

We don't currently have this level of granularity in our config, but the 2.8 release has a few improvements that will make this level of configuration hopefully unnecessary. Our goal is to be smarter by default :)

If you are interested and willing to be on the bleeding edge, you can try running our development build `sourcegraph/server:insiders` and let us know if your problems are solved or if you run into any new issues.

**Comment by ruhullahshah** [comment]
Thanks for all the information. We will try out 2.8 and see how the load is :)

**Comment by nicksnyder** [comment]
@ruhullahshah Were you able to confirm that 2.8 fixed your issue?

**Comment by ruhullahshah** [comment]
@nicksnyder I have enabled the auto Git updates once again but haven't received any abnormal traffic notifications as of now. I can provide a strict confirmation by next week,

**Comment by ruhullahshah** [comment]
@nicksnyder Hi. The load to our GitLab server is normal now with Sourcegraph-2.8 (Git auto updates enabled). Cheers

**Comment by nicksnyder** [comment]
Thanks for confirming!
